'use client';

import React, { useState } from 'react';
import { ProtectedRoute } from '@/components/ProtectedRoute';
import { ReportProvider, useReport } from '@/context/ReportContext';
import ReportHeader from '@/components/reports/ReportHeader';
import TransactionReport from '@/components/reports/TransactionReport';
import AccountReport from '@/components/reports/AccountReport';
import AuditReport from '@/components/reports/AuditReport';
// import SnapshotReport from '@/components/reports/SnapshotReport';
import { AlertTriangle, CheckCircle, Printer } from 'lucide-react';
import SnapshotReport from "@/components/reports/SnapshotReport";

const ReportsContent: React.FC = () => {
    const [activeTab, setActiveTab] = useState('transactions');

    const renderActiveTab = () => {
        switch (activeTab) {
            case 'transactions':
                return <TransactionReport />;
            case 'accounts':
                return <AccountReport />;
            case 'audit':
                return <AuditReport />;
            case 'snapshot':
                return <SnapshotReport />;
            default:
                return <TransactionReport />;
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-950 p-4 md:p-6 print:bg-white print:dark:bg-white">
            <div className="max-w-7xl mx-auto">
                <ReportHeader
                    title="Banking Reports"
                    description="Comprehensive reports and analytics for transactions, accounts, and system activities"
                    activeTab={activeTab}
                    onTabChange={setActiveTab}
                />

                {/* رسائل النظام */}
                <div className="mb-6 space-y-3 print:hidden">
                    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-900/30 rounded-lg p-4 flex items-start gap-3">
                        <Printer className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
                        <div>
                            <p className="text-sm text-blue-800 dark:text-blue-300">
                                Reports are optimized for printing. Use the print button for best results.
                            </p>
                        </div>
                    </div>
                </div>

                {/* محتوى التقرير */}
                <div className="print:bg-white print:dark:bg-white print:shadow-none">
                    {renderActiveTab()}
                </div>

                {/* تعليمات الطباعة (تظهر فقط عند الطباعة) */}
                <div className="hidden print:block mt-8 pt-8 border-t border-slate-800">
                    <div className="text-xs text-slate-600 space-y-2">
                        <p><strong>Confidential Banking Report</strong></p>
                        <p>Generated by BankSys Reporting System</p>
                        <p>Date: {new Date().toLocaleDateString()}</p>
                        <p>Time: {new Date().toLocaleTimeString()}</p>
                        <p className="mt-4">This document contains confidential banking information.</p>
                        <p>Unauthorized distribution is prohibited.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

const ReportsPage: React.FC = () => {
    return (
        <ProtectedRoute>
            <ReportProvider>
                <ReportsContent />
            </ReportProvider>
        </ProtectedRoute>
    );
};

export default ReportsPage;